Feature/47
Bside-Team-Four/popo-server pull request #49
Opened 2023-05-01 09:09 UTC by seofield

2023-05-02 12:54 UTC, Deserve82 requested changes
아까 확인한 유저 생성할 때에 reward 자동으로 안들어가는 이슈도 확인하면 될 거 같습니다~! 잘 작성해주셨습니다. 감사합니다! 👍

2023-05-06 06:14 UTC, seofield commented on src/main/java/com/bside/popo/user/domain/hint/Hint.java
> +    private List<HintPurchase> purchases;
삭제했습니다

2023-05-06 06:14 UTC, seofield commented on src/main/java/com/bside/popo/user/application/hint/HintService.java
> +    private Integer getPriceByHintSeq(Integer hintSeq) {
위치 변경했습니다

2023-05-06 06:29 UTC, seofield commented on src/main/java/com/bside/popo/user/application/hint/HintService.java
> +            hintPurchaseRepository.findByUserIdAndHintId(user, hint)
수정했습니다~!

2023-05-06 10:58 UTC, seofield commented on src/main/java/com/bside/popo/user/application/hint/HintService.java
> +                        user.updateReward(reward - price);
updateReward 는 private으로 변경하고 관련 로직 deductReward로 구현했습니다

2023-05-06 11:30 UTC, merged