[COIN-001]리워드 지급
Bside-Team-Four/popo-server pull request #64
Opened 2023-05-07 08:30 UTC by seofield

2023-05-07 11:34 UTC, Deserve82 requested changes
잘 작성해 주셨습니다~ 몇개만 수정해주면 완벽할 거 같아요!!

2023-05-07 11:34 UTC, Deserve82 commented on src/main/java/com/bside/popo/poll/application/VoteStateService.java
> +        if (state.getCurrQuestionIndex().equals(state.getTotalQuestionCount())) {
이것도 state 내부에 isLastQuestionIndex() 라는 메소드로 VoteState 테스터블하게 내부에서 확인하면 더 좋을 거 같아요!

2023-05-07 11:34 UTC, Deserve82 commented on src/main/java/com/bside/popo/user/domain/user/User.java
> +        this.updateReward(reward + 100);
이것도 100 상수 값이 아니라  변수로 받을 수 있게 하면 좋을 거 같아요!

2023-05-07 11:34 UTC, Deserve82 commented on src/main/java/com/bside/popo/poll/application/QuestionService.java
> +        return questionRepository.countByReleaseDt(new QuestionReleaseDatetime(LocalDateTime.now().plusMinutes(5)));
여기에서는 왜 5분 더하신신걸까요?

2023-05-11 15:00 UTC, seofield commented on src/main/java/com/bside/popo/user/domain/user/User.java
> +        this.updateReward(reward + 100);
증가되는 값을 어디에 저장하거나 어디서 받아야할지가 애매해서 이렇게 했었는데요. 
변수로 받는다고해도 값을 지정해줄곳이 애매한듯한데, 
User클래스에 private static final int REWARD_INCREMENT = 100; 이렇게 상수값을 넣어서 처리하는건 어떤가요?

2023-05-12 01:26 UTC, Deserve82 approved these changes
lgtm! 바로 머지 할 게요!

2023-05-12 01:28 UTC, merged